/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
[34m[1mwandb[39m[22m: [33mWARNING[39m The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
  0%|                                                                                                                                                            | 0/9500 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/p44/PCDF/train.py", line 129, in <module>
    trainer.train()
  File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/transformers/trainer.py", line 1932, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/transformers/trainer.py", line 2230, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/accelerate/data_loader.py", line 454, in __iter__
    current_batch = next(dataloader_iter)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/p44/PCDF/train.py", line 55, in __getitem__
    image = Image.open(image_path).convert("RGB")
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/PIL/Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/p44/PCDF/chart2text_statista/image/two_col/imgs/4084.png'
[rank0]: Traceback (most recent call last):
[rank0]:   File "/p44/PCDF/train.py", line 129, in <module>
[rank0]:     trainer.train()
[rank0]:   File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/transformers/trainer.py", line 1932, in train
[rank0]:     return inner_training_loop(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/transformers/trainer.py", line 2230, in _inner_training_loop
[rank0]:     for step, inputs in enumerate(epoch_iterator):
[rank0]:   File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/accelerate/data_loader.py", line 454, in __iter__
[rank0]:     current_batch = next(dataloader_iter)
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
[rank0]:     data = self._next_data()
[rank0]:            ^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
[rank0]:     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:             ~~~~~~~~~~~~^^^^^
[rank0]:   File "/p44/PCDF/train.py", line 55, in __getitem__
[rank0]:     image = Image.open(image_path).convert("RGB")
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/wani/anaconda3/envs/corning/lib/python3.12/site-packages/PIL/Image.py", line 3431, in open
[rank0]:     fp = builtins.open(filename, "rb")
[rank0]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: FileNotFoundError: [Errno 2] No such file or directory: '/p44/PCDF/chart2text_statista/image/two_col/imgs/4084.png'